/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Artists {
  artist_description: string | null;
  artist_id: Generated<string>;
  artist_name: string;
  img_url: string | null;
  type_id: number;
  website_url: string | null;
}

export interface ArtistsGenres {
  artist_id: string;
  genre_id: number;
}

export interface ArtistsSeries {
  artist_id: string;
  series_id: string;
}

export interface ArtistTypes {
  type_description: string;
  type_id: number;
}

export interface EventReviewLikes {
  datetime_created: Generated<Timestamp | null>;
  like_id: string;
  review_id: string;
}

export interface EventReviews {
  datetime_created: Generated<Timestamp | null>;
  event_id: string;
  rating: number;
  review_id: Generated<string>;
  review_text: string | null;
  user_id: string;
}

export interface Events {
  cancelled: Generated<boolean | null>;
  event_begin_date: Timestamp;
  event_description: string | null;
  event_end_date: Timestamp | null;
  event_id: Generated<string>;
  event_name: string;
  event_time: string | null;
  img_url: string | null;
  series_id: string;
  setlist_id: string | null;
  tickets_required: Generated<boolean | null>;
  tickets_url: string | null;
  type_id: number;
  venue_id: string;
}

export interface EventsArtists {
  artist_id: string;
  event_id: string;
}

export interface EventTypes {
  type_description: string;
  type_id: number;
}

export interface GenreTypes {
  type_description: string;
  type_id: number;
}

export interface GroupsMembers {
  group_id: string;
  member_id: string;
}

export interface HashAlgorithmTypes {
  type_description: string;
  type_id: number;
}

export interface RelationshipTypes {
  type_description: string;
  type_id: number;
}

export interface RoleTypes {
  type_description: string;
  type_id: number;
}

export interface Series {
  avg_rating: Generated<Numeric | null>;
  img_url: string | null;
  series_description: string | null;
  series_id: Generated<string>;
  series_name: string;
  type_id: number;
}

export interface SeriesTypes {
  type_description: string;
  type_id: number;
}

export interface Setlists {
  setlist_description: string | null;
  setlist_id: Generated<string>;
}

export interface SubgenresTypes {
  genre_id: number;
  type_description: string;
  type_id: number;
}

export interface UserAccounts {
  active: Generated<boolean | null>;
  email: string;
  hash_algorithm_id: number;
  password_hash: string;
  password_salt: string;
  role_id: number;
  user_id: Generated<string>;
  username: string;
}

export interface UserProfiles {
  address_line: string | null;
  city: string | null;
  country: string | null;
  date_of_birth: Timestamp | null;
  first_name: string;
  gender: string | null;
  last_name: string;
  pfp_url: string | null;
  phone_number: string | null;
  postal_code: string | null;
  region: string | null;
  user_id: string;
}

export interface UserRelationships {
  datetime_created: Generated<Timestamp | null>;
  follower_id: string;
  following_id: string;
  relationship_type_id: number;
}

export interface VenueReviewLikes {
  datetime_created: Generated<Timestamp | null>;
  like_id: string;
  review_id: string;
}

export interface VenueReviews {
  datetime_created: Generated<Timestamp | null>;
  event_id: string;
  rating: number;
  review_id: Generated<string>;
  review_text: string | null;
  user_id: string;
  venue_id: string;
}

export interface Venues {
  avg_rating: Generated<Numeric | null>;
  img_url: string | null;
  type_id: number;
  venue_description: string | null;
  venue_id: Generated<string>;
  venue_name: string;
  website_url: string | null;
}

export interface VenuesSeries {
  series_id: string;
  venue_id: string;
}

export interface VenueTypes {
  type_description: string;
  type_id: number;
}

export interface DB {
  artist_types: ArtistTypes;
  artists: Artists;
  artists_genres: ArtistsGenres;
  artists_series: ArtistsSeries;
  event_review_likes: EventReviewLikes;
  event_reviews: EventReviews;
  event_types: EventTypes;
  events: Events;
  events_artists: EventsArtists;
  genre_types: GenreTypes;
  groups_members: GroupsMembers;
  hash_algorithm_types: HashAlgorithmTypes;
  relationship_types: RelationshipTypes;
  role_types: RoleTypes;
  series: Series;
  series_types: SeriesTypes;
  setlists: Setlists;
  subgenres_types: SubgenresTypes;
  user_accounts: UserAccounts;
  user_profiles: UserProfiles;
  user_relationships: UserRelationships;
  venue_review_likes: VenueReviewLikes;
  venue_reviews: VenueReviews;
  venue_types: VenueTypes;
  venues: Venues;
  venues_series: VenuesSeries;
}
